
  version: "3.9"
  services:
    backend:
      image: ivory
      ports:
        - "5000:5000"
      environment:
        - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
        - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
        - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      env_file:
        - .env

    
 
