version: '3.8'

services:
  backend:
    image: ivory
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./ivory-project-457721-2d60ad88afc9.json:/app/ivory-project-457721-2d60ad88afc9.json
