import { ComponentType } from 'react';
import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiCplusplus,
  SiSharp as SiCSharp,
  SiGo,
  SiRust,
  SiRuby,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiScala,
  SiDart,
  SiR,
  SiApple,
  SiGnubash,
  SiPowers as SiPowershell,
  SiHtml5,
  SiCss3,
  SiSass,
  SiLess,
  SiJson,
  SiYaml,
  SiMarkdown,
  SiReact,
  SiVuedotjs,
  SiSvelte,
  SiGraphql,
  SiMysql,
  SiPostgresql,
  SiSqlite,
  SiDocker,
  SiGithub as SiGit,
  SiNpm,
  SiYarn,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiStylelint,
  SiToml,
  SiXml,
  SiNodedotjs
} from 'react-icons/si';
import {
  FileArchive,
  FileAudio,
  FileCode as FileCodeIcon,
  FileImage,
  FileSpreadsheet,
  FileText,
  FileVideo,
  File,
} from 'lucide-react';

// Language to icon mapping with programming language icons
export const languageIcons: Record<string, ComponentType<{ className?: string }>> = {
  // Programming Languages
  'javascript': SiJavascript,
  'js': SiJavascript,
  'typescript': SiTypescript,
  'ts': SiTypescript,
  'python': SiPython,
  'py': SiPython,
  'java': FileCodeIcon,
  'c': SiCplusplus,
  'cpp': SiCplusplus,
  'c++': SiCplusplus,
  'c#': SiCSharp,
  'csharp': SiCSharp,
  'go': SiGo,
  'golang': SiGo,
  'rust': SiRust,
  'rs': SiRust,
  'ruby': SiRuby,
  'rb': SiRuby,
  'php': SiPhp,
  'swift': SiSwift,
  'kotlin': SiKotlin,
  'kt': SiKotlin,
  'scala': SiScala,
  'dart': SiDart,
  'r': SiR,
  'objective-c': SiApple,
  'objc': SiApple,
  'shell': SiGnubash,
  'bash': SiGnubash,
  'sh': SiGnubash,
  'zsh': SiGnubash,
  'powershell': SiPowershell,
  'ps1': SiPowershell,
  'html': SiHtml5,
  'htm': SiHtml5,
  'css': SiCss3,
  'sass': SiSass,
  'scss': SiSass,
  'less': SiLess,
  'json': SiJson,
  'yaml': SiYaml,
  'yml': SiYaml,
  'markdown': SiMarkdown,
  'md': SiMarkdown,
  'text': FileText,
  'txt': FileText,
  'jsx': SiReact,
  'tsx': SiTypescript,
  'vue': SiVuedotjs,
  'svelte': SiSvelte,
  'graphql': SiGraphql,
  'sql': SiMysql,
  'mysql': SiMysql,
  'postgresql': SiPostgresql,
  'postgres': SiPostgresql,
  'sqlite': SiSqlite,
  'dockerfile': SiDocker,
  'docker': SiDocker,
  'gitignore': SiGit,
  'gitattributes': SiGit,
  'git': SiGit,
  'editorconfig': FileCodeIcon,
  'npmrc': SiNpm,
  'yarnrc': SiYarn,
  'babelrc': SiBabel,
  'babel': SiBabel,
  'eslintrc': SiEslint,
  'eslint': SiEslint,
  'prettierrc': SiPrettier,
  'prettier': SiPrettier,
  'stylelintrc': SiStylelint,
  'stylelint': SiStylelint,
  'toml': SiToml,
  'xml': SiXml,
  'node': SiNodedotjs,

  // File types
  'svg': FileImage,
  'png': FileImage,
  'jpg': FileImage,
  'jpeg': FileImage,
  'gif': FileImage,
  'webp': FileImage,
  'ico': FileImage,
  'webm': FileVideo,
  'mp4': FileVideo,
  'mov': FileVideo,
  'avi': FileVideo,
  'wmv': FileVideo,
  'mp3': FileAudio,
  'wav': FileAudio,
  'ogg': FileAudio,
  'pdf': FileText,
  'doc': FileText,
  'docx': FileText,
  'xls': FileSpreadsheet,
  'xlsx': FileSpreadsheet,
  'csv': FileSpreadsheet,
  'zip': FileArchive,
  'rar': FileArchive,
  '7z': FileArchive,
  'tar': FileArchive,
  'gz': FileArchive,
  'bz2': FileArchive,
  'exe': FileCodeIcon,
  'dll': FileCodeIcon,
  'so': FileCodeIcon,
  'dmg': FileCodeIcon,
  'pkg': FileCodeIcon,
  'deb': FileCodeIcon,
  'rpm': FileCodeIcon,
};

// Helper function to get the appropriate icon for a language
export const getLanguageIcon = (language: string | null | undefined) => {
  if (!language) return File;
  const normalizedLang = language.toLowerCase();
  return languageIcons[normalizedLang] || File;
};
